name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: game
        path: ${{github.workspace}}/build/bin/Release
        
    - name: Publish Artifacts
      uses: ncipollo/release-action@v1
      with:
        tag: 'binaries'
        artifacts: ${{github.workspace}}/build/bin/Release/*
        body: "Latest game executable"
        token: ${{ secrets.GITHUB_TOKEN }}
      
      
